feat: capture extra log file for waste
bcgov-nr/nr-funbucks pull request #658
Opened 2024-09-04 17:27 UTC by andrwils

2024-09-04 17:29 UTC, GraceRuan approved these changes

2024-09-04 18:00 UTC, mbystedt requested changes
Will not capture rotated .2, .3, ...

2024-09-04 18:19 UTC, andrwils commented
> Will not capture rotated .2, .3, ...

@mbystedt Should we add simply exclude .gz files for all services? Then we could go with a wildcard in the logs path override. Or we could instead treat this as an unusual circumstance and just use a ? wildcard on a per-service level as needed.

2024-09-04 18:35 UTC, mbystedt commented
> > Will not capture rotated .2, .3, ...
> 
> @mbystedt Should we exclude .gz files for all services? Then we could go with a wildcard in the logs path override. Or we could instead treat this as an unusual circumstance and just use a ? wildcard on a per-service level as needed.

Excluding .gz and maybe a couple other common archive types as default makes sense.

2024-09-05 23:24 UTC, mbystedt approved these changes

2024-09-05 23:26 UTC, merged